# Generated by Django 5.0.4 on 2024-04-20 11:05
from django.db import migrations

def add_default_courses(apps, schema_editor):
    Course = apps.get_model('Courses', 'Course')

    # Add default courses
    default_courses = [
        
    {'title': 'Digital Marketing Essentials', 'description': 'Discover the fundamentals of digital marketing and learn how to create effective online marketing strategies. Explore topics such as search engine optimization (SEO), social media marketing, email marketing, content marketing, and paid advertising. Gain practical skills to drive traffic, generate leads, and increase conversions for businesses.', 'amount': 199.99},
    {'title': 'Photography Masterclass', 'description': 'Unlock the secrets of photography in this comprehensive masterclass. Learn about camera settings, composition techniques, lighting principles, and post-processing tools. Dive into different genres of photography, including landscape, portrait, wildlife, and street photography. Develop your creative vision and capture stunning images.', 'amount': 299.50},
    {'title': 'Financial Planning for Beginners', 'description': 'Take control of your finances with this beginner-friendly course on financial planning. Learn how to create budgets, manage debt, save for the future, and invest wisely. Understand key financial concepts such as compound interest, risk management, and retirement planning. Gain the knowledge and confidence to achieve your financial goals.', 'amount': 399.75},
    {'title': 'Graphic Design Fundamentals', 'description': 'Explore the fundamentals of graphic design and unleash your creativity. Learn about typography, color theory, layout principles, and design software tools. Develop practical skills to create logos, posters, brochures, and digital graphics. Build a strong foundation in graphic design and express your ideas visually.', 'amount': 199.99},
    {'title': 'Business Administration Basics', 'description': 'Gain insight into the essentials of business administration and management. Learn about organizational structures, leadership styles, decision-making processes, and project management techniques. Explore topics such as business ethics, communication strategies, and employee motivation. Acquire the skills to effectively manage teams and projects in various business settings.', 'amount': 149.99},
    {'title': 'Creative Writing Workshop', 'description': 'Immerse yourself in the world of creative writing and unleash your imagination. Explore different genres, writing styles, and storytelling techniques. Learn how to develop characters, plot narratives, and craft engaging prose. Receive feedback from experienced writers and refine your writing skills. Whether you\'re a novice or seasoned writer, this workshop will inspire and motivate you to create compelling stories.', 'amount': 249.99},
    

]


    for course_data in default_courses:
        Course.objects.create(**course_data)

class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_courses),
    ]
